//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMinta
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForigenKeyTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ForigenKeyTable()
        {
            this.TableWithForigenKey = new HashSet<TableWithForigenKey>();
        }
    
        public int nid { get; set; }
        public string KulsoAdat1 { get; set; }
        public Nullable<bool> Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TableWithForigenKey> TableWithForigenKey { get; set; }
    }
}
