//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMinta
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cnMintaDb : DbContext
    {
        public cnMintaDb()
            : base("name=cnMintaDb")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ForigenKeyTable> ForigenKeyTable { get; set; }
        public virtual DbSet<SingleTable> SingleTable { get; set; }
        public virtual DbSet<TableWithForigenKey> TableWithForigenKey { get; set; }
    }
}
