//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMinta
{
    using System;
    using System.Collections.Generic;
    
    public partial class SingleTable
    {
        public int nid { get; set; }
        public string Adat1 { get; set; }
        public Nullable<decimal> Adat2 { get; set; }
        public Nullable<System.DateTime> Adat3 { get; set; }
        public Nullable<int> Adat4 { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
